[package]
name = "blink"
version = "0.0.1"

[features]
default = ["mcu_k20"]
mcu_k20 = ["zinc/mcu_k20"]

[dependencies]
zinc = { path =  "../.." }
macro_zinc = { path = "../../macro_zinc" }
rust-libcore = "*"
